# wrangler.toml

name = "api"
main = "app/index.ts"
compatibility_date = "2025-08-03"
compatibility_flags = ["nodejs_compat"]

[[hyperdrive]]
binding = "PORTFOLIO_HYPERDRIVE"
id = "4fd49cba02174cc0ba0fec837f42f792"
localConnectionString = "postgres://postgres:mysecretpassword@localhost:5050/dev-db"

[observability.logs]
enabled = true

[vars]
COOKIE_DOMAIN = ".roninubermensch.workers.dev"
ORIGIN = "https://app.roninubermensch.workers.dev"


